#!/bin/bash

set -eu

cd "$(dirname $0)"

rm -rf tpcds-kit
git clone https://github.com/databricks/tpcds-kit.git
cd tpcds-kit/tools
make -j$(nproc) OS=LINUX
mkdir -p $SPARKSGX_DATA_DIR/tpcds/data/
./dsdgen -SCALE 1 -DELIMITER , -DIR $SPARKSGX_DATA_DIR/tpcds/data/ -FORCE
chmod u+r $SPARKSGX_DATA_DIR/tpcds/data/*.dat

# Go through all of the files and manually reduce by 10x
FILES=$SPARKSGX_DATA_DIR/tpcds/data/*.dat
for f in $FILES
do
    cp $f $f.copy
    sed -n '1p;0~10p' $f.copy > $f
    rm $f.copy
done


